### PR TITLE
Refactor tooling integration (#403)

### PR DESCRIPTION
**Pull request by jpommerening**
Hi!

This is a long diff (sorry) and a long description as well, but I didn't have the time to write a shorter one.

#### Here's the plan to overhaul the tooling API (tl;dr)

1. build static debug information with `laxar-loader/debug-info`
2. gather dynamic state via a super-global `debugEventBus` shared across instances
3. enable multiple instances to announce their tooling APIs on `window.laxarInstances`
4. upgrade the tools to use `window.laxarInstances[*].tooling` instead of the old `laxarDeveloperToolsApi`

#### The nitty gritty

`laxar-loader` generates a new artifact containing debug info, for example: `laxar-loader/debug-info?flow=main`. I planned for this to make use of `bundle-loader?lazy` so requiring it will actually provide a callback to load the debug info asynchronously when and if we need it.

This alone almost makes the current "pages collector" approach obsolete. All the static information we need will be present in the debug bundle. We still need something else to collect dynamic information, like the current page (well, currently, that is all we need, but I could think of more). For this I decided to create another EventBus instance, called `debugEventBus`.

This is where most of the diff stems from. I passed the `debugEventBus` to all loaders so they will be able to notify the tooling when they load & unload stuff. In some places this new `debugEventBus` replaces the `toolingProviders`, in other places I just added it as a new argument. Speaking of `toolingProviders`: erase that word from your memory, it's now called `tooling` throughout.

The `axTooling` injection is mostly the same as before. I duplicated the tooling provider's `pages` API for compatibility and was able to get the `ax-developer-tools-widget` working with it. I also successfully used the widget as a bridge to get the Chrome extension working by assigning the global object that the widget uses to communicate with it's window to the object that is polled by the Chrome extension. (`laxarDeveloperToolsApi = axDeveloperTools`)

About the new `debugEventBus`: _all_ Laxar 2 instances that are present on a page and enable tooling in their config share _one_ `debugEventBus`, so events will have to be namespaced (not the case yet).

The way this works is that when instances are bootstrapped, a shared `debugEventBus` is picked from any other global Laxar instance and passed to the service creation function. Only Laxar instances with tooling support appear globally. If no other Laxar instance was discovered, a `debugEventBus` is created on the fly in the service creation method. If we want to be picky, we could check if we're running in tooling disabled mode and return a noop-EventBus in this case but I have not implemented that.

#### What still missing

- [ ] a new, stable, future-proof tooling API
- [ ] namespaced debug events
- [ ] docs
- [ ] tests
- [ ] updated extensions, widget

@alex3683 @x1B @jonaswjs: I need your help with the first two points. How do we name events and where do we fire them to create a dynamic map of currently "active" artifact instances?

### CODE REVIEW

**Comment by x1B** [comment]
Alright, I am positively thrilled! 👍  

The namespacing of debug events ties in directly with the namespacing of widget-IDs across instances, for unique subscriber and DOM IDs.

The instances themselves are already named, so we should include that information into the names of the debug events for easy pattern matching.

Then, within instances, there can be several pages, or standalone widgets at the same time. I'll call these _...bootstrapping items._ 🎺  Those we could simply count up in the order they are registered on their bootstrapping context. Finally, there is the good old widget ID as generated by the page loader, which is page-wide unique.

So, maybe a starting point for discussion would be something like:

```js
debugEventBus.publish( `didEnterPage.myApp.item4`, {
   page: `some-use-case/cool-page`,
   place: null, // only used within flows
   instance: 'myApp',
   bootstrappingItem: "item4"
   bootstrappingType: 'page'
} );
```

Of course, the dev tools extension/widget needs some additional logic to use this intel in order to match the unprefixed widget IDs from their debug bundle against the prefixed widget IDs from the event bus inspector.

We could also allow developers to name their bootstrapping items using an additional option to `.page, .flow` and so on, making it easier to use the dev tools.

**Comment by x1B** [comment]
Maybe event `didEnterPage` is a bad choice as it does not encompass standalone widgets.
Perhaps something like `didLoad.page.myApp.item4` and `didLoad.widget.myApp.item5`.

**Comment by jpommerening** [comment]
I like `didLoad`, since it pretty much answers where the event comes from (a loader). Will there be a `didUnload`? In the final example, are `page` and `widget` static strings?

I guess we can't just use the instance and bootstrapping item name directly, but have to encode/escape it so it satisfies the topic-format right? Maybe we should call that string derived from the name an `id`? :)

**Comment by x1B** [comment]
Yeah, that is correct. We should also plan for `didUnload` as you suggest. We'll most definitely want to add an API to destroy a bootstrapping instance, so the dev tools need to know. Also, we can say unload during page transitions within flows.

**Comment by jpommerening** [comment]
Ok, I added a new `instanceContext` object to be created during bootstrapping and passed around where one needs to generate unique IDs or interact with the debugEventBus.
Actual structure of that object is TBD of course.

I also switched to `didLoad` & `didUnload` events, now published by the PageService.

Aaaand I added a `BootstrappingInstance.page` method to bootstrap a page instead of a flow (you can not use both, though … _yet_). This may be removed before 2, but I find it useful to have it for manually testing/evaluating the different scenarios.

**Comment by jpommerening** [comment]
Trying out a new tooling API to be notified of changes in a specific bootstrap item or the whole instance:

```js
tooling.forInstance().onChange( callback );
tooling.forItem( instanceContext ).onChange( callback );

// where instanceContext is the "thing" that is currently
// passed to the page service et al to build event subtopics
```

The data passed to the callback currently contains properties identifying the instance and the bootstrap item, as well as the thing that changed. Needs some refactoring still, but its getting there.

**Comment by jpommerening** [comment]
Btw. the `onChange` callback is now invoked with the following object (and I hope this to be close to its final form):

```
const event = {
   instance: 'name-id0', // the instance ID
   item: 'bootstrapitem-id0', // the ID of the bootstrapping item,
   pages: {
      'ref/or/my-page': { ...debugInfo }
   },
   widgets: {
      'ref/of/my-widget': { ...debugInfo }
   }
};
// where debugInfo is whatever object was created by laxar-loader for this particular widget or page
```

Each time the stuff that is active in a particular bootstrapping item changes, this callback fires with updated lists. The event data is enough to build the previous pages tooling (`lib/tooling/pages`) upon, and with it the developer tools (+widget).

**Comment by jpommerening** [comment]
@x1B, @alex3683: I'm happy with how it looks now, how about I squash+rebase+merge this so we can all use it and iron out the wrinkles that will appear?

**Comment by alex3683** [comment]
Go ahead!

**Comment by x1B** [comment]
make it so

**Pull request merged**
